### ISSUE TITLE
关于 BLUETOOTH_PRIVILEGED权限问题

### ISSUE THREAD

**Issue by zbcloading** [litesuits/android-lite-bluetoothLE#8]
FATAL EXCEPTION: main
                                                                  Process: cn.com.sate.TPMS, PID: 10562
                                                                  java.lang.SecurityException: Need BLUETOOTH_PRIVILEGED permission: Neither user 10110 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
                                                                      at android.os.Parcel.readException(Parcel.java:1620)
                                                                      at android.os.Parcel.readException(Parcel.java:1573)
                                                                      at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerForNotification(IBluetoothGatt.java:1148)
                                                                      at android.bluetooth.BluetoothGatt.setCharacteristicNotification(BluetoothGatt.java:1170)
                                                                      at com.litesuits.bluetooth.conn.LiteBleConnector.setCharacteristicNotification(LiteBleConnector.java:295)
                                                                      at com.litesuits.bluetooth.conn.LiteBleConnector.enableCharacteristicNotification(LiteBleConnector.java:215)
                                                                      at com.litesuits.bluetooth.conn.LiteBleConnector.enableCharacteristicNotification(LiteBleConnector.java:205)
                                                                      at cn.com.sate.TPMS.TPMSInterface.enableNotificationOfCharacteristic(TPMSInterface.java:141)
                                                                      at cn.com.sate.TPMS.TPMSInterface$1$2.run(TPMSInterface.java:74)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

在使用enableCharacteristicNotification方式时，报错 系统提示缺少BLUETOOTH_PRIVILEGED
这个问题该怎么解决呢？

**Comment by zbcloading** [comment]
这个问题解决了。
原因在于UUID，我这个设备用到的UUID与google申明必须要拥有系统权限才能使用的四条UUID正好一样，于是才会有以上问题。只需要让蓝牙方　更换一下使用的UUID  就可以了。
