### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by xvolica** [litesuits/android-lite-bluetoothLE#9]
示例程序报错
W/BluetoothGatt: Unhandled exception in callback
       java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

**Comment by xvolica** [comment]
`W/BluetoothGatt: Unhandled exception in callback
                                                                      java.util.ConcurrentModificationException
                                                                          at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
                                                                          at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
                                                                          at com.litesuits.bluetooth.LiteBluetooth$2.onServicesDiscovered(LiteBluetooth.java:350)
                                                                          at android.bluetooth.BluetoothGatt$1.onSearchComplete(BluetoothGatt.java:305)
                                                                          at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:217)
                                                                          at android.os.Binder.execTransact(Binder.java:452)`
